//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzeriaEntities : DbContext
    {
        public PizzeriaEntities()
            : base("name=PizzeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorii> Kategoriis { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Meni> Menis { get; set; }
        public virtual DbSet<Naracka> Narackas { get; set; }
        public virtual DbSet<Opi> Opis { get; set; }
        public virtual DbSet<PoedinecnaPica> PoedinecnaPicas { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<Velicina> Velicinas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
