//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naracka
    {
        public int NarackaID { get; set; }
        public Nullable<int> MeniID { get; set; }
        public Nullable<int> KorisniciID { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Meni Meni { get; set; }
    }
}
